Weather envelope
IM3S/LDAR_Sim pull request #94
Opened 2021-08-12 23:14 UTC by AkaMrmuffin

Add a built-in weather envelope for the weather checks. The specific thresholds for the weather envelope needs to be discussed.

2021-08-12 23:16 UTC, AkaMrmuffin commented
#21

2021-08-13 18:53 UTC, KeeganShaw-GIS requested changes
Nice work, update all Default Parameters to include default ranges, and update the documentation, then we can merge.

2021-08-13 18:53 UTC, KeeganShaw-GIS commented on LDAR_Sim/model_code/weather/weather_lookup.py
> +        temp_env = [0, 0]
Should be set in Default Parameters , and Temperature low should be less than 0

2021-09-22 01:13 UTC, KeeganShaw-GIS commented
Added into followup PR #111

2021-09-22 01:13 UTC, closed without merging